# This file uses Control-h as a prefix
# but is otherwise a great usable tmux configuration

set -gu prefix2
# set -g mouse on
unbind C-b
unbind C-a
set-option -g prefix C-h
bind-key C-h send-prefix

bind p previous-window
bind n next-window
bind j join-pane
bind N new-session

# Make C-o select next pane, and r rotate panes.
# i always hit `prefix control-o` on accident when i mean `prefix o`
bind o select-pane -t :.+
bind C-o select-pane -t :.+
bind r rotate-window

# Layout shortcuts
bind v select-layout main-vertical
bind h select-layout main-horizontal
bind i select-layout tiled

# Save pane history to dated directory
bind-key S run-shell '~/code/dot-files/tmux/tmux-save-pane.sh'

# Splitting windows with - and | instead of " and %
bind - split-window -v
bind | split-window -h
# unbind previous splits
unbind '"'
unbind %

# If reattach-to-user-namespace is needed for clipboard support
set-option -g default-command "$SHELL"

# Set cursor style
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
# Set the default cursor to a vertical bar
set -g default-terminal "xterm-256color"

set-option -g editor "vim" # emacs

# Update window status to show names
set -g automatic-rename on
set -g automatic-rename-format "#W"
set -g window-status-format "#I: #W"
set -g window-status-current-format "#[bold]#I: #W#[default]"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# set -g @plugin 'catppuccin/tmux#v2.1.2'
# set -g @plugin 'dracula/tmux'
set -g @ayu_time_format "%I:%M %p"

set -g @plugin 'TechnicalDC/tmux-ayu-theme'
set -g @ayu_date_format "%D"

# set -g @plugin "nordtheme/tmux
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
