# This file uses Control-h as a prefix
# but is otherwise a great usable tmux configuration

set -gu prefix2
unbind C-b
unbind C-a
set-option -g prefix C-h
bind-key C-h send-prefix
bind p previous-window
bind n next-window
bind j join-pane

# Splitting windows with - and | instead of " and %
bind - split-window -v
bind | split-window -h
# unbind previous splits
unbind '"'
unbind %

set-option -g default-command "reattach-to-user-namespace -l $SHELL"


set-option -g editor "emacsclient -nw" # emacs

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'


# set -g @plugin "nordtheme/tmux"

# set -g @plugin 'Nybkox/tmux-kanagawa'
# set -g @kanagawa-theme 'dragon'
# set -g @kanagawa-plugins "cpu-usage ram-usage"
# set -g @kanagawa-show-powerline true
set -g @plugin 'catppuccin/tmux#v2.1.2'
# set -g @plugin "olimorris/tmux-pomodoro-plus"
# set -g @plugin "wabri/tmux-nord-plusplus"
# set -g @plugin 'dracula/tmux'

# set -g @plugin 'dracula/tmux'



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'